### ISSUE TITLE
will there be any liunux binaries any time soon?

### ISSUE THREAD

**Issue by its-19818942118** [mariiaan/cmdplay-pp#8]
just asking i know it will take time but seeing as macos havin it. so i thought may be you gave up on the idea of it. :)

**Comment by mariiaan** [comment]
Hi, yeah that kind of works already. There are some things like controls or colours which don't work yet. Just take a look at the linprep branch. You should find a makefile (linux.Makefile) there. 

In the first few lines of that makefile, the required libraries are listed which you'll need to install.

I will close this issue now due to it being a duplicate (please refer to the "linux binaries" issue).

I'd be glad to hear from you about this! Just ask me if you have further questions (via discord or the "linux binaries" issue)

Thank you for your interest!

**Comment by its-19818942118** [comment]
> Hi, yeah that kind of works already. There are some things like controls or colours which don't work yet. Just take a look at the linprep branch. You should find a makefile (linux.Makefile) there.
> 
> In the first few lines of that makefile, the required libraries are listed which you'll need to install.
> 
> I will close this issue now due to it being a duplicate (please refer to the "linux binaries" issue).
> 
> I'd be glad to hear from you about this! Just ask me if you have further questions (via discord or the "linux binaries" issue)
> 
> Thank you for your interest!

yeah hey sure. um so i send a friend request to you pls check that names sirusliy_not_rahman.

**Comment by its-19818942118** [comment]
@mariiaan i tested out the linux binaries there are some well typos. and rendering is not smooth keeps breaking on update etc. breaking as not the program breaking but that the rendering of the frmaes and stuff is not smooth it has buffer times which kinda ruins it. but could be how i setup my environment. also how do i contanct on discord cuz i cant reach you.

**Comment by mariiaan** [comment]
The video smoothness is not an issue of cmdplay-pp. 
As for me, it runs well in a native terminal session. It does lag in the default ubuntu terminal emulator.
So you should try switching to another TTY (native session).

The buffer times are a problem of the new version (different audio backend). This is going to be fixed some day.

**Comment by its-19818942118** [comment]
@mariiaan hey. sorry if i am bothering you. its been a long time. 😓 wanted to reach out to you in discord. but i cannot find you there 😓 .if you still have discord can you tell me the username? 😅
